# Generated by Django 4.2.2 on 2023-06-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Project',
        ),
    ]
